apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 2
  selector:
    matchLabels: { app: hello }
  template:
    metadata:
      labels: { app: hello }
    spec:
      containers:
      - name: nginx
        image: ghcr.io/ajoparker/gitops-hello
        newTag: "sha-0223477"
        ports:
          - containerPort: 80